
# To run the containers, use the command:
# docker-compose up -d
# Access the web server at http://localhost:8080
version: '3.8'

services:
  xampp-web:
    build: .
    container_name: xampp-web
    ports:
      - "8050:80"
    environment:
      - DB_HOST=xampp-db
      - DB_NAME=xampp_shareride_db
      - DB_USER=root
      - DB_PASSWORD=Gustave@123
    depends_on:
      - xampp-db
    volumes:
      - ./src:/var/www/html
    networks:
      - xampp-network

  xampp-db:
    image: mariadb:latest
    container_name: xampp-db
    environment:
      - MYSQL_ROOT_PASSWORD=Gustave@123
      - MYSQL_DATABASE=xampp_shareride_db
    ports:
      - "3307:3306"
    volumes:
      - xampp-db-data:/var/lib/mysql
    networks:
      - xampp-network

  xampp-phpmyadmin:
    image: phpmyadmin:latest
    container_name: xampp-phpmyadmin
    environment:
      - PMA_HOST=xampp-db
      - PMA_USER=root
      - PMA_PASSWORD=Gustave@123
    ports:
      - "8051:80"
    depends_on:
      - xampp-db
    networks:
      - xampp-network

volumes:
  xampp-db-data:

networks:
  xampp-network:
    driver: bridge
